package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	rootDir := "."
	if err := processPackages(rootDir); err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}
}

func processPackages(rootDir string) error {
	return filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if !info.IsDir() {
			return nil
		}

		return processPackage(path)
	})
}

func processPackage(pkgPath string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, pkgPath, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("failed to parse package %s: %v", pkgPath, err)
	}

	var resetMethods []resetMethod

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			resetMethods = append(resetMethods, findResetStructs(file)...)
		}
	}

	if len(resetMethods) == 0 {
		return nil
	}

	return generateResetFile(pkgPath, resetMethods)
}

type resetMethod struct {
	StructName string
	Fields     []fieldInfo
}

type fieldInfo struct {
	Name  string
	Type  string
	IsPtr bool
}

func findResetStructs(file *ast.File) []resetMethod {
	var methods []resetMethod

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			if hasGenerateResetComment(genDecl) {
				methods = append(methods, createResetMethod(typeSpec.Name.Name, structType))
			}
		}
	}

	return methods
}

func hasGenerateResetComment(decl *ast.GenDecl) bool {
	if decl.Doc == nil {
		return false
	}

	for _, comment := range decl.Doc.List {
		if strings.TrimSpace(strings.TrimPrefix(comment.Text, "//")) == "generate:reset" {
			return true
		}
	}
	return false
}

func createResetMethod(structName string, structType *ast.StructType) resetMethod {
	method := resetMethod{StructName: structName}

	if structType.Fields == nil {
		return method
	}

	for _, field := range structType.Fields.List {
		for _, name := range field.Names {
			fieldType := exprToString(field.Type)
			fieldInfo := fieldInfo{
				Name:  name.Name,
				Type:  fieldType,
				IsPtr: isPointerType(field.Type),
			}

			method.Fields = append(method.Fields, fieldInfo)
		}
	}

	return method
}

func exprToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + exprToString(t.X)
	case *ast.ArrayType:
		return "slice"
	case *ast.MapType:
		return "map"
	default:
		return fmt.Sprintf("%v", expr)
	}
}

func isPointerType(expr ast.Expr) bool {
	_, ok := expr.(*ast.StarExpr)
	return ok
}

func generateResetFile(pkgPath string, methods []resetMethod) error {
	outputFile := filepath.Join(pkgPath, "reset.gen.go")

	pkgName := filepath.Base(pkgPath)

	var buf bytes.Buffer

	buf.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	buf.WriteString("package " + pkgName + "\n\n")

	for _, method := range methods {
		generateMethod(&buf, method)
		buf.WriteString("\n")
	}

	return os.WriteFile(outputFile, buf.Bytes(), 0644)
}

func generateMethod(buf *bytes.Buffer, method resetMethod) {
	receiver := strings.ToLower(string(method.StructName[0]))

	buf.WriteString("func (" + receiver + " *" + method.StructName + ") Reset() {\n")
	buf.WriteString("\tif " + receiver + " == nil {\n")
	buf.WriteString("\t\treturn\n")
	buf.WriteString("\t}\n\n")

	for _, field := range method.Fields {
		if field.IsPtr {
			buf.WriteString("\tif " + receiver + "." + field.Name + " != nil {\n")
			if isUserType(field.Type) {
				buf.WriteString("\t\tif resetter, ok := interface{}(" + receiver + "." + field.Name + ")." + "(interface{ Reset() }); ok && " + receiver + "." + field.Name + " != nil {\n")
				buf.WriteString("\t\t\tresetter.Reset()\n")
				buf.WriteString("\t\t}\n")
			} else if field.Type == "*slice" {
				buf.WriteString("\t\t" + receiver + "." + field.Name + " = " + receiver + "." + field.Name + "[:0]\n")
			} else if field.Type == "*map" {
				buf.WriteString("\t\tclear(" + receiver + "." + field.Name + ")\n")
			} else {
				buf.WriteString("\t\t*" + receiver + "." + field.Name + " = " + getZeroValue(field.Type) + "\n")
			}
			buf.WriteString("\t}\n")
		} else {
			if isUserType(field.Type) {
				buf.WriteString("\tif resetter, ok := interface{}(" + receiver + "." + field.Name + ")." + "(interface{ Reset() }); ok && " + receiver + "." + field.Name + " != nil {\n")
				buf.WriteString("\t\tresetter.Reset()\n")
				buf.WriteString("\t}\n")
			} else if field.Type == "slice" {
				buf.WriteString("\t" + receiver + "." + field.Name + " = " + receiver + "." + field.Name + "[:0]\n")
			} else if field.Type == "map" {
				buf.WriteString("\tclear(" + receiver + "." + field.Name + ")\n")
			} else {
				buf.WriteString("\t" + receiver + "." + field.Name + " = " + getZeroValue(field.Type) + "\n")
			}
		}
	}

	buf.WriteString("}\n")
}

func isUserType(typeName string) bool {
	switch {
	case strings.HasPrefix(typeName, "int"), strings.HasPrefix(typeName, "uint"),
		strings.HasPrefix(typeName, "float"), strings.HasPrefix(typeName, "complex"):
		return false
	case typeName == "string":
		return false
	case typeName == "bool":
		return false
	case typeName == "slice":
		return false
	case typeName == "map":
		return false
	case strings.HasPrefix(typeName, "*"):
		return isUserType(strings.TrimLeft(typeName, "*"))
	default:
		return true
	}
}

func getZeroValue(typeName string) string {
	switch {
	case strings.HasPrefix(typeName, "int"), strings.HasPrefix(typeName, "uint"),
		strings.HasPrefix(typeName, "float"), strings.HasPrefix(typeName, "complex"):
		return "0"
	case typeName == "string":
		return `""`
	case typeName == "bool":
		return "false"
	case strings.HasPrefix(typeName, "*"):
		return getZeroValue(strings.TrimLeft(typeName, "*"))
	default:
		return "type_not_supported"
	}
}
